
-- 1. COMPARISON OPERATOR

-- RETRIVE ALL CUSTOMERS FROM GERMANY
SELECT *
FROM customer
WHERE country = 'Germany'

-- RETRIVE ALL CUSTOMERS WHO ARE NOT FROM GERMANY

SELECT *
FROM customer
WHERE country != 'Germany' --<>

-- RETRIVE ALL CUSTOMERS WITH SCORE GREATER THAN 500
SELECT *
FROM customers
WHERE score > 500

-- RETRIVE ALL CUSTOMERS SCORE 500 OR MORE
SELECT * 
FROM customer
WHERE score >=500

-- RETRIVE ALL CUSTOMERS WITH A SCORE LESS THAN 500
SELECT *
FROM customer
WHERE score < 500

-- RETRIVE ALL CUSTOMERS WITH A SCORE OF 500 OR LESS
SELECT *
FROM customer
WHERE score <= 500