-- DDL 
-- CREATE A NEW TABLE CALLED PERSONS WITH COLUMNS : ID, PERSON_NAME , BIRTH_DATE AND PHONE_NMBER

CREATE TABLE personss (
    id INT NOT NULL,
    person_name VARCHAR(50) NOT NULL,
    birth_date DATE,
    phone VARCHAR(15) NOT NULL,
    CONSTRAINT pk_personss PRIMARY KEY (id)
);
