-- ADD A NEW COLUMN CALLED EMAIL TO THE PERSONSS TABLE

/*ALTER TABLE personss
ALTER COLUMN email VARCHAR(50) NOT NULL;
GO

SELECT * FROM personss;*/

--REMOVE THE COLUMN PHONE FROM THE PERSON TABLE

--ALTER TABLE personss
--DROP COLUMN phone

--SELECT * FROM personss

--DELETE THE TABLE PERSONSS FROM THE DATABASE

DROP TABLE personss
