-- LEFT ANTI JOIN = RETURNS ROW FROM LEFT THAT HAS NO MATCH IN RIGHT

-- SYNTAX =
--SELECT *
--FROM A
--LEFT JOIN B
--ON A.KEY = B.KEY
-- WHERE B.KEY IS NULL

-- THE ORDER OF THE TABLE IS IMP

-- GET ALL CUSTOMERS WHO HAVEN'T PLKACED ANY ORDERS


SELECT *
FROM customers AS c
LEFT JOIN orders AS o
ON c.id = o.customer_id
WHERE o.customer_id IS NULL
