-- LOGICAL OPERATOR

-- 1. AND OPERATOR = ALL CONDITIONS MUST BE TRUE


-- retrive all customers who are from usa and have score greater than 500

SELECT *
FROM customers
WHERE country = 'USA' AND score > 500

-- 2. OR OPERATOR = ATLEAST ONE CONDITION MUST BE TRUE

-- RETRIVE ALL CUSTOMERS WHO ARE EITHER FROM USA OR HAVE A SCORE GREATERTHAN 500 

SELECT *
FROM customers
WHERE country = 'USA' OR score > 500


-- 3. NOT OPERATOR = REVRSE MATHCING VALUE

-- RETRIE ALL CUSTOMERS WITH A SCORE NOT LESS THAN 500

SELECT *
FROM customers
WHERE NOT score < 500