-- WHY WE NEED JOINS
-- 1. RECOMBINE DATA
-- 2. DATA ENRICHMENT "GETTING EXTRA DATA"
-- 3.  CHECK FOR EXISTENCE "FILTERING"

-- JOINS TYPES
-- BASICS--
-- NO JOIN
-- INNER JOIN
-- LEFT JOIN
-- RIGHT JOIN

-- ADVANCED--
-- LEFT ANTI JOIN
-- RIGHT ANTI JOIN
-- CROSS JOIN


-- NO JOIN = RETURNS DATA FROM TABLES WITHOUT COMBINING THEM
-- RETRIVE ALL DATA FROM CUSTOMERS AND ORDERS AS SEPARATE RESULTS

SELECT * 
FROM customers;

SELECT *
FROM orders

--SELECT DB_NAME() AS CurrentDatabase;USE MyDatabase;GO

