-- RANGE OPERATOR

-- BETWEEN = CHECK IF THE VALUE IS WITHIN A RANGE

-- RETRIVE ALL CUSTOMERS WHOSE SCORE FALLS IN THE RANGE BETWEEN 100 AND 500

SELECT *
FROM customers
WHERE score BETWEEN 100 AND 500 

-- WITH COMPARISON OPERATOR
SELECT *
FROM customers
WHERE score >=100 AND score <= 500 