-- RIGHT JOIN
-- RETURNS ALL ROWS FROM RIGHT AND ONLY MATCHING FROM LEFT

-- ORDER OF TABLE IS IMP

-- GET ALL CUSTOMERS ALONG WITH
-- THEIR ORDERS INCLUDING ORDERS WITHOUT MATCHING CUSTOMERS

SELECT
	c.id,
	c.first_name,
	o.order_id,
	o.sales
FROM customers AS c
RIGHT JOIN orders AS o
ON c.id = o.customer_id
