-- RIGHT ANTI JOIN 

-- RETURN ROWS FROM RIGHT TABLE THAT HAS NO MATCH IN LEFT

-- SYNTAX =
--SELECT *
--FROM A
-- RIGHT JOIN B
--ON A.KEY = B.KEY
-- WHERE A.KEY IS NULL

-- THE ORDER OF THE TABLE IS IMP

-- GET ALL ORDERS WITHOUT MATCHING CUSTOMERS

SELECT *
FROM  customers AS c 
RIGHT JOIN  orders AS o
ON  c.id =  o.customer_id 
WHERE c.id IS NULL


-- GET ALL ORDERS WITHOUT MATCHING CUSTOMERS CUSTOMERS LEFT JOIN
SELECT *
FROM  orders AS o
LEFT JOIN customers AS c
ON  c.id =  o.customer_id 
WHERE c.id IS NULL
