-- SET UNION OPERATOR

-- RETURNS ALL DISTRICT ROWS FROM BOTH QUERIES
-- REMOVES DUPLICATES ROWS FROM THE RESULT
-- ORDER OF QUERIES IN A UNION OPERATION DOES NOPT AFFECT THE RESULT

-- TASK : COMBINE THE DATA FROM EMPLYOEE AND CUSTOMERS INTO ONE TABLE

SELECT 
FirstName,
LastName
FROM Sales.Customers

UNION

SELECT 
FirstName,
LastName
FROM Sales.Employees

