-- SET UNION ALL

-- RETURNS ALL ROWS FROM BOTH QUERIES , INCLUDING DUPLICATES

-- WHEN TO USE UNION ALL vs UNION

-- IF YOU'RE CONFIUDENT THERE ARE NO DUPLICATES , USE UNION ALL
-- USE UNION ALL TO FIND DUPLICATES AND QUALITY ISSUES

-- TASK : COMBINE THE DATA FROM EMPLYOEES AND CUSTOMERS INTO ONE TABLE INCLUDING DUPLICATES

SELECT 
FirstName,
LastName
FROM Sales.Customers

UNION ALL

SELECT 
FirstName,
LastName
FROM Sales.Employees

