-- CROSS JOIN 

-- COMBINES EVERY ROW FROM LEFT WITH EVERY ROW FROM RIGHT
-- ALL POSSIBLE COMBINATION - CARTESIAN JOIN

-- syntax 
-- SELECT *
-- FROM A
-- CROSS JOIN B
-- NO CONDITION

-- TABLE ORDER DOES NOT MATTER

-- GENERATE ALL POSSIBLE COMBINATIONS OF CUSTOMERS AND ORDERS

SELECT *
FROM customers
CROSS JOIN orders 